apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: wordpress
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 # Optional for NodePort
  type: NodePort 
